apiVersion: v1
kind: ResourceQuota
metadata:
  name: israheck-site
  namespace: israheck-site
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hard:
    requests.cpu: 100m
    requests.memory: 128Mi
    limits.cpu: 500m
    limits.memory: 256Mi
    pods: "6"
    services: "4"

