apiVersion: v1
kind: ResourceQuota
metadata:
  name: external-dns
  namespace: external-dns
spec:
  hard:
    pods: "2"
    requests.cpu: 200m
    requests.memory: 256Mi
    requests.ephemeral-storage: 256Mi
    limits.cpu: 500m
    limits.memory: 512Mi
    limits.ephemeral-storage: 1Gi
